version: '3'

services:
  mariadb:
    image: mariadb:10.6
    container_name: docker-mariadb
    environment:
      MARIADB_DATABASE: iesjaroso
      MARIADB_USER: usuario
      MARIADB_PASSWORD: usuario
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql:rw
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
             --default-authentication-plugin=mysql_native_password
    
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dockerfile
    container_name: docker-php
    ports:
      - "8080:80"
    volumes:
      - ../tema7/regalosNavidad:/var/www/html
    depends_on:
      - mariadb
    
volumes:
  data:
    driver: local